// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUa7VigtvaExgN7QKOND_vl_JteZBZNUs',
    appId: '1:468567739846:web:99d2c921d20db7b9ffb6c7',
    messagingSenderId: '468567739846',
    projectId: 'strobilus-19bf2',
    authDomain: 'strobilus-19bf2.firebaseapp.com',
    storageBucket: 'strobilus-19bf2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzaYTHeSwPhxPQA_icmeZA2eMffcAvwLA',
    appId: '1:468567739846:android:fbe89f67421d6206ffb6c7',
    messagingSenderId: '468567739846',
    projectId: 'strobilus-19bf2',
    storageBucket: 'strobilus-19bf2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC52u-31OE9lhyJEb2rOeGcC0oelqCw59E',
    appId: '1:468567739846:ios:6e76ad96ea8bc66cffb6c7',
    messagingSenderId: '468567739846',
    projectId: 'strobilus-19bf2',
    storageBucket: 'strobilus-19bf2.firebasestorage.app',
    iosBundleId: 'com.strobilus.strobilus',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC52u-31OE9lhyJEb2rOeGcC0oelqCw59E',
    appId: '1:468567739846:ios:6e76ad96ea8bc66cffb6c7',
    messagingSenderId: '468567739846',
    projectId: 'strobilus-19bf2',
    storageBucket: 'strobilus-19bf2.firebasestorage.app',
    iosBundleId: 'com.strobilus.strobilus',
  );
}
